title: Karanpal Singh
author: Karanpal Singh
email: karanpal.singh@alumni.ubc.ca
description: > # this means to ignore newlines until "show_exerpts:"
 Hi, This is my 2nd Blog.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /MyBlog2

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Karanpal Singh
  tagline: UBC MDS 2019-20 Student
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: thelehhman
    github:  thelehhman
    linkedIn: in/thelehhman
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
 theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
